on:
  deployment_status: [success]
name: Check Markdown links for modified files
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Set target URL env
      run:
        echo "DEPLOYMENT_URL=${{ github.event.deployment_status.target_url }}" >> $GITHUB_ENV
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        file-extension: 'mdx'
        check-modified-files-only: 'yes'
        folder-path: 'website/content'
