on: [pull_request]
name: Check Markdown links for modified files
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Wait for Vercel preview deployment to be ready
      uses: patrickedqvist/wait-for-vercel-preview@master
      id: waitForVercelPreviewDeployment
      with:
       token: ${{ secrets.GITHUB_TOKEN }}
       max_timeout: 300
    - name: Set target URL env
      run:
        echo "DEPLOYMENT_URL=${{ needs.waitForVercelPreviewDeployment.outputs.url }}" >> $GITHUB_ENV
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        file-extension: 'mdx'
        folder-path: 'website/content'
