on: [pull_request]
name: Check Markdown links for modified files
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
    steps:
    - name: Wait for Vercel preview deployment to be ready
      uses: patrickedqvist/wait-for-vercel-preview@master
      id: waitForVercelPreviewDeployment
      with:
       token: ${{ secrets.GITHUB_TOKEN }}
       max_timeout: 60
    - name: Set target URL env
      run:
        echo "DEPLOYMENT_URL=${{ needs.test_setup.outputs.preview_url }}" >> $GITHUB_ENV
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        file-extension: 'mdx'
        check-modified-files-only: 'yes'
        folder-path: 'website/content'
